services:
  - type: web
    name: tradutor-neutro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application  # Note "application" aqui
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.13"